export const ME_REQUEST = "ME_REQUEST";
export const ME_SUCCESS = "ME_SUCCESS";
export const ME_FAILURE = "ME_FAILURE";

export const ME_POSTS_REQUEST = "ME_POSTS_REQUEST";
export const ME_POSTS_SUCCESS = "ME_POSTS_SUCCESS";
export const ME_POSTS_FAILURE = "ME_POSTS_FAILURE";

export const ME_PICTURES_REQUEST = "ME_PICTURES_REQUEST";
export const ME_PICTURES_SUCCESS = "ME_PICTURES_SUCCESS";
export const ME_PICTURES_FAILURE = "ME_PICTURES_FAILURE";

export const ME_AVATAR_REQUEST = "ME_AVATAR_REQUEST";
export const ME_AVATAR_SUCCESS = "ME_AVATAR_SUCCESS";
export const ME_AVATAR_FAILURE = "ME_AVATAR_FAILURE";

export const ME_POST_PICTURES_REQUEST = "ME_POST_PICTURES_REQUEST";
export const ME_POST_PICTURES_SUCCESS = "ME_POST_PICTURES_SUCCESS";
export const ME_POST_PICTURES_FAILURE = "ME_POST_PICTURES_FAILURE";

export const ME_FRIENDS_REQUEST = "ME_FRIENDS_REQUEST";
export const ME_FRIENDS_SUCCESS = "ME_FRIENDS_SUCCESS";
export const ME_FRIENDS_FAILURE = "ME_FRIENDS_FAILURE";

export const ME_ACCEPT_INVITATION_REQUEST = "ME_ACCEPT_INVITATION_REQUEST";
export const ME_ACCEPT_INVITATION_SUCCESS = "ME_ACCEPT_INVITATION_SUCCESS";
export const ME_ACCEPT_INVITATION_FAILURE = "ME_ACCEPT_INVITATION_FAILURE";
