export const ME_REQUEST = "ME_REQUEST";
export const ME_SUCCESS = "ME_SUCCESS";
export const ME_FAILURE = "ME_FAILURE";

export const ME_FRIENDS_REQUEST = "ME_FRIENDS_REQUEST";
export const ME_FRIENDS_SUCCESS = "ME_FRIENDS_SUCCESS";
export const ME_FRIENDS_FAILURE = "ME_FRIENDS_FAILURE";

export const ME_ACCEPT_INVITATION_REQUEST = "ME_ACCEPT_INVITATION_REQUEST";
export const ME_ACCEPT_INVITATION_SUCCESS = "ME_ACCEPT_INVITATION_SUCCESS";
export const ME_ACCEPT_INVITATION_FAILURE = "ME_ACCEPT_INVITATION_FAILURE";
