export const USER_REQUEST = "USER_REQUEST";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAILURE = "USER_FAILURE";
export const USER_ADD_TO_FRIENDS_REQUEST = "USER_ADD_TO_FRIENDS_REQUEST";
export const USER_ADD_TO_FRIENDS_SUCCESS = "USER_ADD_TO_FRIENDS_SUCCESS";
export const USER_ADD_TO_FRIENDS_FAILURE = "USER_ADD_TO_FRIENDS_FAILURE";
