export const USER_REQUEST = "USER_REQUEST";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAILURE = "USER_FAILURE";

export const USER_POSTS_REQUEST = "USER_POSTS_REQUEST";
export const USER_POSTS_SUCCESS = "USER_POSTS_SUCCESS";
export const USER_POSTS_FAILURE = "USER_POSTS_FAILURE";

export const USER_ADD_TO_FRIENDS_REQUEST = "USER_ADD_TO_FRIENDS_REQUEST";
export const USER_ADD_TO_FRIENDS_SUCCESS = "USER_ADD_TO_FRIENDS_SUCCESS";
export const USER_ADD_TO_FRIENDS_FAILURE = "USER_ADD_TO_FRIENDS_FAILURE";
